### ISSUE TITLE
Function() init <-- how to pass an argument into init function

### ISSUE THREAD

**Issue by ilshookim** [felixblaschke/shelf_plus#14]
I'd like to pass an isolation unique id (uid) to init function when shelfRun().

**1. like this:**

```dart
final uid = 1;
shelfRun(isolated(uid),
  defaultBindAddress: '127.0.0.1',
  defaultBindPort: 9000,
  defaultEnableHotReload: false,
  defaultShared: true);

Handler isolated(final uid) {
  print('isolation: uid=$uid');  // <-- passed the uid in isolated function from outside
  ...
}
```

**2. example full source:**

```
/pubsepc.yaml

name: shelf_plus_multiple_isolation_example
description: shelf_plus example.
version: 1.0.0

environment:
  sdk: '>=2.16.2 <3.0.0'


dependencies:
  # A simple package for working with multithreading, using an interface similar to tasks in C#.
  ossa: ^1.0.2

  # Shelf Plus is a quality of life addon for your server-side development within the Shelf platform.
  shelf_plus: ^1.2.2

  # A shelf handler that wires up a listener for every connection.
  shelf_web_socket: ^1.0.1

dev_dependencies:
  lints: ^1.0.0
```

/bin/shelf_plus_multiple_isolation_example.dart

```dart
import 'dart:io';
import 'dart:convert';

import 'package:shelf_plus/shelf_plus.dart';
import 'package:ossa/ossa.dart';

bool isNull<T>(T obj) => obj == null;
int  epoch() => DateTime.now().millisecondsSinceEpoch;
void print0(Object? object) { }

void main(List<String> arguments) async {
  const multiTreading = true;
  if (multiTreading) {
    final hyperThreading = true;
    final cores = Platform.numberOfProcessors;
    final isolations = hyperThreading ? cores * 2 : cores;
    for (var uid=0; uid<isolations; uid++) {

      late Task task;
      task = await Task.run((context) {
        final uid = context.get('uid');
        if (isNull(uid)) throw FormatException();

        shelfRun(isolated,                // <-- shelfRun(isolated(uid),
          defaultBindAddress: '127.0.0.1',
          defaultBindPort: 9000,
          defaultEnableHotReload: false,
          defaultShared: true);

        return {
          'succeed': true,
          'uid': uid,
        };
      },
      data: {
        'uid': uid,
      },
      onDone: (value) async {
        print0(value);
      },
      onError: (error) async {
        print('uid=$uid, err=${error.object.toString()}');
        task.dispose();
      });

    }
  }

  shelfRun(isolated,                      // <-- shelfRun(isolated(null),
    defaultBindAddress: '127.0.0.1',
    defaultBindPort: 9000,
    defaultEnableHotReload: false,
    defaultShared: true);
}

Handler isolated() {                      // <-- isolated(final uid)
  // print('isolation: uid=$uid');

  final connections = {};
  final app = Router().plus;
  final hello = 'Hello, World!';

  app.get('/', () => hello);
  app.get('/text', () => hello);

  app.get('/json', () => {'say': hello, 'epoch': epoch()});
  
  app.get('/class', () => Person('Theo'));
  app.get('/list', () => [Person('Theo'), Person('Bob')]);

  app.get('/iterable', () => [1, 10, 100].where((n) => n > 9));

  app.get('/html', (req) => '<h1>$hello</h1>', use: typeByExtension('html'));

  app.get('/binary', () => File('nexus3.pdf').openRead());
  app.get('/file', () => File('nexus3.pdf'));

  app.get('/client/<id>', (req, id) => 'client: id=$id');
  app.get('/clientId/<id>', (Request req) => 'client: id=${req.routeParameter('id')}');

  app.get('/ws', () async => WebSocketSession(
    onOpen: (ws) async {
      final sid = DateTime.now().microsecondsSinceEpoch;
      connections[ws] = sid;
      print('ws.onOpen: sid=$sid');
    },
    onMessage: (ws, message) async {
      // t4-t1: total duration
      // t2-t1: sending
      // t3-t2: processing
      // t4-t3: receiving
      final int ts2 = epoch();
      final Map payload = json.decode(message);
      final int sid = connections[ws];
      payload['ts2'] = ts2;
      payload['sid'] = sid;
      final int ts3 = epoch();
      payload['ts3'] = ts3;
      final encoded = json.encode(payload);
      ws.send(encoded);
    },
    onError: (ws, error) {
      final int sid = connections[ws];
      print('ws.onError: sid=$sid, error=$error');
    },
    onClose: (ws) async {
      final int sid = connections[ws];
      connections.remove(ws);
      print('ws.onClose: sid=$sid');
    },
  ));

  app.get('/echo', () async => WebSocketSession(
    onOpen: (ws) async {
      print('ws.onOpen: echo');
    },
    onMessage: (ws, message) async {
      ws.send(message);
    },
    onError: (ws, error) {
      print('ws.onError: error=$error');
    },
    onClose: (ws) async {
      connections.remove(ws);
      print('ws.onClose: echo');
    },
  ));

  return app;
}

class Person {
  final String name;

  Person(this.name);

  Map<String, dynamic> toJson() => {'name': name};
}
```

would you make it this? ^^
thank you.
